### ISSUE TITLE
Allow receiving/transmitting of raw IQ values

### ISSUE THREAD

**Issue by rjzak** [atlas0fd00m/rfcat#58]
For my project, I'm looking at the Yard Stick One as a potential radio. But for my purposes, I need to bypass the firmware's modulation support and deal with raw IQ values, and it seems the YS1/rfcat doesn't allow this. Not setting a modulation scheme defaults to 2FSK.

I propose a MOD_NULL mode which returns the I and Q values interleaved. In transmit mode, it would do expect the same thing, interleaved values. I can't find where the modulation code is in the firmware to take a closer look at how it works.

**Comment by atlas0fd00m** [comment]
although that sounds *awesome*, it is not possible.  RfCat makes use of the *hardware* radio, which includes demodulation.  RfCat never deals with I/Q values, which is why you can't find the code to do so.  the CC1101 radio (which is built into the CC1111 chip used for RfCats) is TI's effort to support almost every known ISM-band radio technology with real hardware (not SDR).  if you want access to I/Q values, you'll need to work with an SDR like the HackRF, BladeRF, LimeSDR, or USRP.  Or, if you only want to receive data, the RTL-SDR's are acceptable $20 SDR dongles for most things.

**Comment by rjzak** [comment]
Understood, thank you for the information!

**Comment by brandonros** [comment]
To clarify, this means the $29 device from Amazon `RTL-SDR Blog V3 R820T2 RTL2832U 1PPM TCXO HF Bias Tee SMA Software Defined Radio with Dipole Antenna Kit` is not compatible with rfcat, correct?
