### ISSUE TITLE
Bootloader issue

### ISSUE THREAD

**Issue by aristoder** [atlas0fd00m/rfcat#88]
Little new to linux. I'm trying to update my newly bought yardstick one. Completely failed to do that on fedora due to sdcc issues. On VM, I installed Ubuntu 20.04 and got all the requirements complete. But, when running the make command, I'm met with this:

==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 622 lines, wrote 1199: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force && sleep 1 ; fi ;
rfcat_bootloader /dev/RFCAT_BL_YS1 erase_all
Traceback (most recent call last):
  File "/usr/local/bin/rfcat_bootloader", line 4, in <module>
    __import__('pkg_resources').run_script('rfcat==1.9.3', 'rfcat_bootloader')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/rfcat-1.9.3-py3.8.egg/EGG-INFO/scripts/rfcat_bootloader", line 243, in <module>
  File "/usr/local/lib/python3.8/dist-packages/rfcat-1.9.3-py3.8.egg/EGG-INFO/scripts/rfcat_bootloader", line 102, in erase_all_user
  File "/usr/local/lib/python3.8/dist-packages/pyserial-3.5b0-py3.8.egg/serial/serialposix.py", line 598, in write
    d = to_bytes(data)
  File "/usr/local/lib/python3.8/dist-packages/pyserial-3.5b0-py3.8.egg/serial/serialutil.py", line 65, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: ':00000023DD\n'
make: *** [Makefile:378: installRfCatYS1CCBootloader] Error 1

Any guess on what's causing this? Thank you in advance.

**Comment by atlas0fd00m** [comment]
@aristoder @oosfoos please check out the latest commit and let me know if this resolves this issue.

thanks!

**Comment by atlas0fd00m** [comment]
please accept my humblest apologies for the delays here.  i've been having difficulties with my dongles' bootloaders and finding and putting the tools together to install bootloaders (or finding the cache of RfCats with good BLs) has taken far more time than i care to admit.  my magic GoodFET i used to use when shipping my own units, well, apparently it ran off with the spoon.  today i cleaned my office and found many things (including my CC-debugger), but not my trusty GoodFET.  time to track down the GreatFET instructions for flashing CC chips!


BTW!  BEFORE ROLLING YOUR OWN BUILDS....  currently SDCC v3.5.0 works great... but the latest on Ubuntu is v3.8.0, which bricks the dongles.  not sure why.  because reflashing *makes use of the RfCat firmware* you'll want to be aware of how to put the dongle into bootloader mode and manually flash the dongle with firmware.  also, some YS1's seem to ship with faulty bootloader code.  i'm not entirely sure why that is.

**Comment by atlas0fd00m** [comment]
closing now.  i believe this is resolved.
