### ISSUE TITLE
YS1 Firmware upgrade

### ISSUE THREAD

**Issue by shinbar1994** [atlas0fd00m/rfcat#91]
Hi
== Hardware ==
Dongle:              b'YARDSTICKONE'
Firmware rev:        b'0348\x00'
Compiler:            Not found! Update needed!
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           603

1. Is it necessary to upgrade YS1 Firmware? if so why? Doesn't the software doing the "magic"?
2. I ran across **rfcrack**  and **rfpwnon** but since Im using python3 i cant use it,is there a way around it?
Thanks
Shimon

**Comment by atlas0fd00m** [comment]
you should be able to use Python2 with the current version of RfCat code.  we're trying to ensure dual-coverage.  please let me know if anything is broken in Py2 or Py3.
you likely have both Py2 and Py3 installed, you should be able to just use python2 to start them.

**Comment by shinbar1994** [comment]
Thanks i will try, i'm sorry for my ignorance but what is the purpose of upgrading firmware?

**Comment by atlas0fd00m** [comment]
i apologize for missing this.
upgrading the firmware can provide additional functionality and bug-fixes.  we've kept the firmware pretty stable for a long time now, but i believe many YS1's ship with a version of firmware which does not include a couple minor updates which can be annoying.  for example, if `d.printRadioConfig()` doesn't include a firmware version/compiler, that's why.
